apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-bad
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-bad
  template:
    metadata:
      labels:
        app: nginx-bad
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 3
          httpGet: 
            path: /fake
            port: 12345
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet: 
            path: /fake
            port: 12345
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
